default:
	cp src/astar.py astar
	cp src/floydwarshall.py floydwarshall
	chmod +x astar
	chmod +x floydwarshall
	cp -r src/AStar .
	cp -r src/FileIO .
	cp -r src/FloydWarshall .
	cp -r src/Graph .
	cp -r src/PriorityQueue .

clean:
	rm astar
	rm floydwarshall
	rm -r AStar
	rm -r FileIO
	rm -r FloydWarshall
	rm -r Graph
	rm -r PriorityQueue

clean-all:
	rm astar
	rm floydwarshall
	rm -r AStar
	rm -r FileIO
	rm -r FloydWarshall
	rm -r Graph
	rm -r PriorityQueue
	rm *.txt
