default:
	cp src/project2.py project2
	chmod +x project2
	cp -r src/ConvexHull .
	cp -r src/FileIO .

clean:
	rm project2
	rm -r ConvexHull
	rm -r FileIO

clean-all:
	rm project2
	rm -r ConvexHull
	rm -r FileIO
	rm *.txt
