default:
	cp src/BucketSort_BubbleSort.py owens-bubblesort
	chmod +x owens-bubblesort
	cp src/BucketSort_QuickSort.py owens-quicksort
	chmod +x owens-quicksort
	cp src/BucketSort_RadixSort.py owens-radixsort
	chmod +x owens-radixsort
	cp src/BucketSort_Driver.py owens-pr01
	chmod +x owens-pr01
	cp -r src/sorters .
	cp src/FileImporter.py .
	cp src/FileWriter.py .

clean:
	rm owens-bubblesort
	rm owens-quicksort
	rm owens-radixsort
	rm owens-pr01
	rm -r sorters
	rm FileImporter.py
	rm FileWriter.py

clean-all:
	rm owens-bubblesort
	rm owens-quicksort
	rm owens-radixsort
	rm owens-pr01
	rm -r sorters
	rm FileImporter.py
	rm FileWriter.py
	rm *.txt
