default:
	cp src/BucketSort_BubbleSort.py owens-bubblesort
	chmod +x owens-bubblesort
	cp src/BucketSort_QuickSort.py owens-quicksort
	chmod +x owens-quicksort
	cp src/BucketSort_RadixSort.py owens-radixsort
	chmod +x owens-radixsort
	cp -r src/sorters .

clean:
	rm owens-bubblesort
	rm owens-quicksort
	rm owens-radixsort
	rm -r sorters	
